-- QuantMore 初始表结构
-- 在 interview-guide 迁移基础上裁剪：删除面试/简历/语音/题库相关表

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'USER',
  default_provider_id VARCHAR(64),
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6),
  CONSTRAINT uk_users_username UNIQUE (username),
  CONSTRAINT users_role_check CHECK (role IN ('USER','ADMIN'))
);

CREATE TABLE knowledge_bases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_count INTEGER,
  category VARCHAR(100),
  chunk_count INTEGER,
  content_type VARCHAR(255),
  file_hash VARCHAR(64) NOT NULL,
  file_size BIGINT,
  last_accessed_at TIMESTAMP(6),
  name VARCHAR(255) NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  question_count INTEGER,
  storage_key VARCHAR(500),
  storage_url VARCHAR(1000),
  uploaded_at TIMESTAMP(6) NOT NULL,
  vector_error VARCHAR(500),
  vector_status VARCHAR(20),
  CONSTRAINT knowledge_bases_vector_status_check
    CHECK (vector_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
  CONSTRAINT idx_kb_hash UNIQUE (file_hash)
);

CREATE TABLE llm_global_setting (
  id BIGINT NOT NULL PRIMARY KEY,
  created_at TIMESTAMP(6) NOT NULL,
  default_chat_provider_id VARCHAR(64) NOT NULL,
  default_embedding_provider_id VARCHAR(64) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE llm_provider_config (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  api_key_ciphertext VARCHAR(4096) NOT NULL,
  api_key_nonce VARCHAR(64) NOT NULL,
  base_url VARCHAR(512) NOT NULL,
  builtin BOOLEAN NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  embedding_dimensions INTEGER,
  embedding_model VARCHAR(128),
  enabled BOOLEAN NOT NULL,
  model VARCHAR(128) NOT NULL,
  supports_embedding BOOLEAN NOT NULL,
  temperature DOUBLE PRECISION,
  updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE rag_chat_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP(6) NOT NULL,
  is_pinned BOOLEAN DEFAULT false,
  message_count INTEGER,
  status VARCHAR(20),
  title VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP(6),
  CONSTRAINT rag_chat_sessions_status_check
    CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE TABLE rag_chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  completed BOOLEAN,
  content TEXT NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  message_order INTEGER NOT NULL,
  type VARCHAR(20) NOT NULL,
  updated_at TIMESTAMP(6),
  session_id BIGINT NOT NULL,
  CONSTRAINT rag_chat_messages_type_check
    CHECK (type IN ('USER', 'ASSISTANT')),
  CONSTRAINT fkfohypaygc0qfqo62vyaxlbntn
    FOREIGN KEY (session_id) REFERENCES rag_chat_sessions(id)
);

CREATE TABLE rag_session_knowledge_bases (
  session_id BIGINT NOT NULL,
  knowledge_base_id BIGINT NOT NULL,
  PRIMARY KEY (session_id, knowledge_base_id),
  CONSTRAINT fkqfob368wcvb82elsjkx2troqu
    FOREIGN KEY (session_id) REFERENCES rag_chat_sessions(id),
  CONSTRAINT fkjsfwqyt1ntgr0fcvjieq8c0nb
    FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id)
);

CREATE TABLE vector_store (
  id UUID DEFAULT public.uuid_generate_v4() NOT NULL PRIMARY KEY,
  content TEXT,
  metadata JSON,
  embedding public.vector(1024)
);

CREATE INDEX idx_kb_category
  ON knowledge_bases (category);
CREATE INDEX idx_rag_message_order
  ON rag_chat_messages (session_id, message_order);
CREATE INDEX idx_rag_message_session
  ON rag_chat_messages (session_id);
CREATE INDEX idx_rag_session_updated
  ON rag_chat_sessions (updated_at);
CREATE INDEX spring_ai_vector_index
  ON vector_store USING hnsw (embedding public.vector_cosine_ops);
